### ISSUE TITLE
Fix failing tests on macOS and Linux

### ISSUE THREAD

**Issue by mdpiper** [permamodel/GIPL-BMI-Fortran#1]
A few tests and example programs are failing on macOS and Linux. Here's the list from the [most recent Travis CI run](https://travis-ci.org/permamodel/GIPL-BMI-Fortran/builds/558033502):

```
The following tests FAILED:
	  3 - test_get_value (SEGFAULT)
	  4 - test_set_value (SEGFAULT)
	 17 - test_get_time_units (Failed)
	 23 - irf_ex (SEGFAULT)
	 24 - get_value_ex (SEGFAULT)
	 25 - set_value_ex (SEGFAULT)
	 27 - change_air_temperature_ex (SEGFAULT)
	 28 - vargrid_ex (SEGFAULT)
Errors while running CTest
``` 

@wk1984 Let's work together to fix these. I'll need the tests working before I can integrate GIPL into pymt. You can add to the [mdpiper/check-build](https://github.com/permamodel/GIPL-BMI-Fortran/tree/mdpiper/check-build) branch that I've created in this repo.

**Comment by wk1984** [comment]
@mdpiper Yes, that is what I mentioned before. These issues might be resulted by diversity between GCC and INTEL compilers. These tests were passed in INTEL. It seems like the codes can not find the files. I guess something wrong in strings. I am still trying to figure out them. Let's exchange information.

**Comment by mdpiper** [comment]
Using the changes in #2, all the tests on Linux are passing (see caveat in #3). Tests are still failing on macOS, though:

```
The following tests FAILED:
	 23 - irf_ex (Child aborted)
	 24 - get_value_ex (Child aborted)
	 25 - set_value_ex (Child aborted)
	 26 - conflicting_instances_ex (Child aborted)
	 27 - change_air_temperature_ex (Child aborted)
	 28 - vargrid_ex (Child aborted)
Errors while running CTest
```

**Comment by mdpiper** [comment]
All tests now passing on Linux and macOS with 4e96d8a.
