### ISSUE TITLE
Fix failing call to get_grid_spacing

### ISSUE THREAD

**Issue by mdpiper** [permamodel/GIPL-BMI-Fortran#3]
In the example program [vargrid_test](https://github.com/permamodel/GIPL-BMI-Fortran/blob/master/GIPL/examples/vargrid_ex.f90), the call to the BMI *get_grid_spacing* function on line 42 causes the program to terminate with a segmentation fault. Commenting out this line serves as a workaround, but the underlying problem should be addressed.

**Comment by wk1984** [comment]
@mdpiper Yes, Mark. I also found this issue as the GIPL model has a non-uniform grid space in Z-axis. I think that is an issue in variable dimension in "vargrid_test". I tried to fix this morning. Did you try the commits (7ce29d8 and others) I posted today? Thanks for all you have done~ Cheers, Kang

**Comment by mdpiper** [comment]
Fixed, philosophically, with changes in #6.
